import = [
  "~/.config/alacritty/themes/themes/palenight.toml"
]
[env]
TERM = "xterm-256color"

[window]
opacity = 0.5
blur = true
padding = { x = 3, y = 3}
dimensions = { columns = 90, lines = 20 }
position = { x = 200, y = 400 }
option_as_alt = "Both"

[font]
size = 20
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[cursor]
style = "Beam"
vi_mode_style = "Block"
