require("config.template")
require("config.mappings")
require("config.lazy")
require("config.lsp_beautiful_hover")
require("config.cmp")
require("config.conform")
require("config.defaults")
require("config.themes")
require("config.mini")
require("config.fm")
require("config.debug")
-- require("config.telescope")
