require("config.template")
require("config.mappings")
require("config.lazy")
-- require("config.lsp")
require("config.lsp_code_errors_info")
require("config.coq")
require("config.conform")
-- require("config.cmp")
require("config.defaults")
require("config.themes")
require("config.mini")
require("config.fm")
require("config.debug")
require("config.fm")
