set -g mouse on

set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM


unbind C-b
set-option -g prefix M-j
bind-key M-j send-prefix

bind -n M-H resize-pane -L 2
bind -n M-L resize-pane -R 2
bind -n M-K resize-pane -U 2
bind -n M-J resize-pane -D 2

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# bind-key k run-shell "~/.config/tmux/tmux_window_manager.sh"
# bind-key k display-popup -E "~/.config/tmux/tmux_window_manager.sh"
bind-key k display-popup -E "~/.config/tmux/tmux_session_manager.sh"
# bind-key k display-popup -E "tms"

set-option -g allow-rename off

# List of plugins

set -g @plugin 'catppuccin/tmux'

# Theme config

set -g @catppuccin_window_status_style "none"
set -g @catppuccin_flavor 'macchiato' # latte, frappe, macchiato or mocha

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-bg default
set -g status-style bg=default
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

# CPU usage
set -gF status-right "#[bg=#{@thm_sapphire},fg=#{@thm_crust}]#[reverse]#[noreverse] "
set -ag status-right "#[fg=#{@thm_fg},bg=#{@thm_bg}] #(macmon pipe -s 1 | jq -r '((.cpu_usage_pct * 100) * 10 | round) / 10') %% "

# Power usage
set -ag status-right "#[bg=#{@thm_yellow},fg=#{@thm_crust}]#[reverse]#[noreverse]󱐋 "
set -ag status-right "#[fg=#{@thm_fg},bg=#{@thm_bg}] #(macmon pipe -s 1 | jq -r '.sys_power | (. * 10 | round) / 10') W "

# RAM usage
set -ag status-right "#[bg=#{@thm_mauve},fg=#{@thm_crust}]#[reverse]#[noreverse] "
set -ag status-right "#[fg=#{@thm_fg},bg=#{@thm_bg}] #(macmon pipe -s 1 | jq -r '.memory.ram_usage | (. / (1024*1024*1024) * 10 | round) / 10') GB "

# CPU temp
set -ag status-right "#[bg=#{@thm_flamingo},fg=#{@thm_crust}]#[reverse]#[noreverse] "
set -ag status-right "#[fg=#{@thm_fg},bg=#{@thm_bg}] #(macmon pipe -s 1 | jq -r '.temp.cpu_temp_avg | (. * 10 | round) / 10')˚C "

# GPU temp
set -ag status-right "#[bg=#{@thm_flamingo},fg=#{@thm_crust}]#[reverse]#[noreverse] "
set -ag status-right "#[fg=#{@thm_fg},bg=#{@thm_bg}] #(macmon pipe -s 1 | jq -r '.temp.gpu_temp_avg | (. * 10 | round) / 10')˚C "

# Session name
set -ag status-right "#{E:@catppuccin_status_session}"
